name: "build and test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install
        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn dev:site
          wait-on: http://localhost:3000
      - name: Cypress reports
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            cypress/reports/
            cypress/screenshots/
            cypress/videos/
          retention-days: 1
